dracoon:
  base_url: https://dracoon.team
logging:
  log_level: info
  log_file:
    log_file_path: dracoon.log
activate_virus_protection: [] # data room ids to activate virus scan in including all sub rooms
