[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Wl,--as-needed",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,-z,relro",
    "-C", "link-arg=-Wl,-z,now"
]
